#!/bin/sh

clear

echo ""
echolor --White "## [START] GIT - PRE-COMMIT"

[ `which echolor` == "" ] && wget -nc -o /usr/local/bin/echolor https://raw.githubusercontent.com/Gruppio/Echolor/master/echolor.sh

export REMOVE_DIRS="vendor,Godeps,node_modules,bower_components,_vendor,dist,CMakeFiles,CMakeScripts"
export REMOVE_DIRS_ARRAY=($(echo "$REMOVE_DIRS" | tr ',' '\n'))

#####################################################################
# If called with no arguments a new timer is returned.
# If called with arguments the first is used as a timer
# value and the elapsed time is returned in the form HH:MM:SS.
#
# function timer
function timer()
{
	if [ $# -eq 0 ]; then
		# echolor --Green "Start timer with ${count_args} args."
        echo $(date '+%s')
    else
		# echolor --Red "End timer with ${count_args} args."
        local stime=$1
        etime=$(date '+%s')
        if [[ -z "$stime" ]]; then stime=$etime; fi
        dt=$((etime - stime))
        ds=$((dt % 60))
        dm=$(((dt / 60) % 60))
        dh=$((dt / 3600))
		printf 'function: "%s", duration: %d:%02d:%02d' "$2" $dh $dm $ds
    fi
}

declare script_start=$(timer)

function separator {
	echo "-----------------------------------------------------------------"
	echo
}

function fbs { 
	local start=$(timer)
	local limit=${1:-"20"}
	du -m . | sort -nr | head -n $limit
	echo $(timer $start $FUNCNAME)
	separator
}

function ls_directory_with_sort_head { 
	local start=$(timer)
	local limit=${1:-"20"}
	du -h . | sort -hr | head -n $limit
	echo $(timer $start $FUNCNAME)
	separator
}

function ls_directory_with_grep_sort_head { 
	local start=$(timer)
	local pattern=${1:-"vendor"}
	local limit=${2:-"50"}
	du -h . | grep "$pattern" | sort -hr | head -n $limit
	echo $(timer $start $FUNCNAME)
	separator
}

function remove_dirs_recursive { 
	local start=$(timer)
	local pattern=${1:-"test"}
	find . -not -path '*/\.git/*' -name "$pattern" -type d -exec rm -rf {} +
	echo $(timer $start $FUNCNAME)
	separator
}

function ls_subtrees {
	local start=$(timer)
	local export_file=${1:-".meta/ls-subtrees.tsv"}
	ensure_dir
	git log | grep -E 'git-subtree-dir|git-subtree-repo' | awk '{ print $2 $3 $4 }' > $export_file ;
	echo $(timer $start $FUNCNAME)
	separator
}

function ls_subtrees_sorted {
	local start=$(timer)
	local export_file=${1:-".meta/ls-subtrees.sorted.tsv"}
	ensure_dir
	git log | grep -e git-subtree-dir -e git-subtree-repo | tr -d ' ' | cut -d ":" -f2 | sort | uniq > $export_file ;
	echo $(timer $start $FUNCNAME)
	separator
}

function ls_subtrees_exists {
	local start=$(timer)
	local export_file=${1:-".meta/ls-subtrees.exists.tsv"}
	ensure_dir
	git log | grep -e git-subtree-dir -e git-subtree-repo | tr -d ' ' | cut -d ":" -f2 | sort | uniq | xargs -I {} bash -c 'if [ -d $(git rev-parse --show-toplevel)/{} ] ; then echo {}; fi' > $export_file ;
	echo $(timer $start $FUNCNAME)
	separator
}

function ls_subtrees_dedup {
	local start=$(timer)
	local export_file=${1:-".meta/ls-subtrees.dedup.tsv"}
	ensure_dir
	git log | grep git-subtree-dir | tr -d ' ' | cut -d ":" -f2 | sort | uniq | xargs -I {} bash -c 'if [ -d $(git rev-parse --show-toplevel)/{} ] ; then echo {}; fi' > $export_file ;
	echo $(timer $start "$FUNCNAME")
	separator
}

function ensure_dir {
	local start=$(timer)
	local prefix_path=${1:-".meta"}
	mkdir -p ${prefix_path}
	echo $(timer $start $FUNCNAME)
}

function ls_dirs_size {
	local start=$(timer)
	local limit=${1:-"50"}
	local export_file=${1:-".meta/ls-dirs.by_size.top${limit}.output"}
	ensure_dir
	du -m . | sort -nr | head -n $limit > ${export_file}
	echo $(timer $start $FUNCNAME)
	separator
}

declare REMOVED_DIRS_TOTAL=0
declare REMOVED_DIRS_KEYS=()
function rm_vendor_dirs { 

	# start timer
	local start=$(timer)

	# function args
	local pattern_dirname=${1:-"test"}
	local prefix_path=${2:-"."}
	local exclude_paths=${3:-'*/\.git/*,*/\.svn/*'}

	# excludes
	# convert to array
	local exclude_paths_array=($(echo "$exclude_paths" | tr ' ' '\n'))

	# patterns
	# get the default patterns for directories to remove
	local patterns_array=${REMOVE_DIRS_ARRAY}

	# result
	local matches=(fs_find ${prefix_path} ${patterns_array} ${excludes_array})
	# local matches=(fs_sift ${prefix_path} ${patterns_array} ${excludes_array})
	# local matches=(fs_fsql ${prefix_path} ${patterns_array} ${excludes_array})
	# local matches=(fs_snkfs ${prefix_path} ${patterns_array} ${excludes_array})

	local matches_array=($(echo "$matches" | tr ' ' '\n'))
	local matches_count=${#matches_array[@]}

	# stop timer
	local time_execution=$(timer $start $FUNCNAME)

	# output summary
	echolor --White  " - pattern_dirname    = ${pattern_dirname}"
	echolor --Cyan   " - matches_count      = ${matches_count}"

	if [ ${matches_count} -gt 0 ]; then
		REMOVED_DIRS_KEYS+=(${pattern_dirname})
		REMOVED_DIRS_TOTAL=$((REMOVED_DIRS_TOTAL+$matches_count))
		echolor --White   " - matches_array       = ${matches_array[@]}"
		echolor --Green   " - matches_count      = ${matches_count}"
	else
		echolor --Red     " - matches_count      = ${matches_count}"
	fi

	echolor --White  " - removed_global_items          = ${REMOVED_DIRS_KEYS[*]}"
	echolor --White  " - removed_global_items_total    = ${REMOVED_DIRS_TOTAL}"
	echolor --Yellow " - time_execution = ${time_execution}"
}

function fs_find() { 
	local prefix_path=${1:-"."}
	local patterns_array=$2
	local excludes_array=$3

	# remove patterns matching
	local patterns_args=""
	for pattern in "${patterns_array[@]}"; do
		patterns_args+=" -name \"$pattern\" "
	done

	local exclude_paths_sequence=""
	for exclude in "${REMOVE_DIRS_ARRAY[@]}"; do
		exclude_paths_sequence+=" -not -path '${exclude}' "
	done

	echolor --Red "find ${prefix_path} -not -path '*/\.git/*' ${patterns_args} -type d -print -exec rm -rf {} +"
	local removed_dirs=$(find ${prefix_path} -not -path '*/\.git/*' ${remove_sequence} -type d -print -exec rm -rf {} +)
	print ${removed_dirs}
}

function fs_snks() {
	local prefix_path=${1:-"."}
	local patterns_array=$2
	local excludes_array=$3

	# remove patterns matching
	local patterns_args=""
	for pattern in "${patterns_array[@]}"; do
		patterns_args+=" -name \"$pattern\" "
	done

	local exclude_paths_sequence=""
	for exclude in "${REMOVE_DIRS_ARRAY[@]}"; do
		exclude_paths_sequence+=" -not -path '${exclude}' "
	done

	echolor --Red "find ${prefix_path} -not -path '*/\.git/*' ${patterns_args} -type d -print -exec rm -rf {} +"
	local removed_dirs=$(find ${prefix_path} -not -path '*/\.git/*' ${remove_sequence} -type d -print -exec rm -rf {} +)
	print ${removed_dirs}
}

function fs_sift() { 
	local prefix_path=${1:-"."}
	local patterns_array=$2
	local excludes_array=$3

	# remove patterns matching
	local patterns_args=""
	for pattern in "${patterns_array[@]}"; do
		patterns_args+=" -name \"$pattern\" "
	done

	local exclude_paths_sequence=""
	for exclude in "${REMOVE_DIRS_ARRAY[@]}"; do
		exclude_paths_sequence+=" -not -path '${exclude}' "
	done

	echolor --Red "find ${prefix_path} -not -path '*/\.git/*' ${patterns_args} -type d -print -exec rm -rf {} +"
	local removed_dirs=$(find ${prefix_path} -not -path '*/\.git/*' ${remove_sequence} -type d -print -exec rm -rf {} +)
	print ${removed_dirs}
}

rm_vendor_dirs

export REMOVE_DIRS_COUNT=${#REMOVE_DIRS_ARRAY[@]}

echo ""
echolor --Cyan "## REMOVE vendoring dirs"
echo "- REMOVE_DIRS_ARRAY: ${REMOVE_DIRS_ARRAY[*]}"
echo ""

declare start
declare elapsed

export GCPRUNEFUL=false
function pruneful {
	local start=$(timer)
	local match="git prune"
	local file=".git/gc.log"
	echo ""
	echolor --Cyan "## CHECK repo is pruneful ?"
	if [ -f ${file} ]; then
		echolor --Red "### found ${file}"
		[ `cat  ${file} | grep -c "$match"` -gt 0 ] && GCPRUNEFUL=true
		if [ "$GCPRUNEFUL" == "true" ]; then
			echo "### removing ${file}"
			rm -f $file
			echo "### Run git prune"
			git prune
		fi
	fi
	echo $(timer $start $FUNCNAME)
	separator
}

pruneful

export COMMITFUL=false
export UNSTAGGED_FILES=""
export UNSTAGGED_FILES_COUNT=0
function ls_unstagged {
	local start=$(timer)
	local result=$(git status --short | grep '^.[^ ]' | sed 's/^...//')
	UNSTAGGED_FILES=($(echo "$result" | tr ' ' '\n'))
	UNSTAGGED_FILES_COUNT=${#UNSTAGGED_FILES[@]}
	echo ""
	echolor --Cyan "## CHECK unstagged files: "
	echolor --Red "$UNSTAGGED_FILES"
	echo ""
	echo "- UNSTAGGED_FILES_COUNT=${#UNSTAGGED_FILES[@]}"
	if [ "${UNSTAGGED_FILES_COUNT}" -gt 0 ]; then 
		COMMITFUL=true
	fi
	echo $(timer $start "$FUNCNAME")
	separator
}

ls_unstagged

rm -fR ./0

export COMMIT_COUNT=0
function git_commit {
	local start=$(timer)
	[ "$COMMIT_COUNT" -gt 2 ] && exit # prevent infinite loops
	local message=${1:-"add latest changes..."}	
	git add .
	git commit -am "$1"
	COMMIT_COUNT=($COMMIT_COUNT+1)
	echo $(timer $start "$FUNCNAME")
	separator
}

echolor --Green "## PRE-COMMIT - SUMMARY"
echo ""

## removed vendor dirs ? 
echolor --Yellow "### CLEAN-UP"
if [ ${REMOVED_DIRS_TOTAL} -gt 0 ]; then
	echolor --Red "- REMOVED_DIRS_KEYS     =   ${REMOVED_DIRS_KEYS[*]}"
	echolor --Red "- REMOVED_DIRS_TOTAL    =   ${REMOVED_DIRS_TOTAL}"
else
	echolor --Green "- REMOVED_DIRS_TOTAL    =   ${REMOVED_DIRS_TOTAL}"
fi
echo ""

## Unstagged files ?
echolor --Yellow    "### CHECKER"
if [ "${UNSTAGGED_FILES_COUNT}" -gt 0 ]; then
	echolor --Red   "- COMMITFUL             =   ${COMMITFUL}"
	echolor --Red   "- UNSTAGGED_FILES_COUNT =   ${UNSTAGGED_FILES_COUNT}"
	echolor --Red   "- UNSTAGGED_FILES       =   ${UNSTAGGED_FILES[*]}"
	git_commit "add unstagged files"
else
	echolor --Green "- COMMITFUL             =   ${COMMITFUL}"
	echolor --Green "- UNSTAGGED_FILES_COUNT =   ${UNSTAGGED_FILES_COUNT}"
fi

## gc prune ?
if [ "${GCPRUNEFUL}" == true ]; then
	echolor --Red   "- GCPRUNEFUL             =   ${GCPRUNEFUL}"
else
	echolor --Green "- GCPRUNEFUL             =   ${GCPRUNEFUL}"
fi

echo ""
echolor --White "## [END] GIT - PRE-COMMIT"
echolor --Yellow $(timer $script_start "pre-commit")
echo ""

# In general my mac is ok with git but if there are a lot of loose objects then it gets very much slower. 
# It seems hfs is not so good with lots of files in a single directory.
# git repack -ad
# git gc --prune=now

# ls_dirs_size
# ls_subtrees
# ls_subtrees_sorted
# ls_subtrees_exists
# ls_subtrees_dedup

# git config core.fileMode false
# git config --global core.autocrlf true

# git rm -r --cached .
# git add -A
# git commit -am 'Removing ignored files'

# ref. https://stackoverflow.com/questions/5787937/git-status-shows-files-as-changed-even-though-contents-are-the-same
# git ls-files --eol

# ref. http://www.codewrecks.com/blog/index.php/2014/04/22/git-showing-file-as-modified-even-if-it-is-unchanged/
# modified files issue
# git config core.autocrlf false

# git reset --hard HEAD~1
# git config --global fetch.prune true
# git config --global gc.auto 1
# git config --local gc.auto 1
# git config -l
# git config remote.origin.prune true
# git config --global gc.auto 0
# git config --global gc.aggressive 0
# git config --local gc.auto 1
# git config --local gc.aggressive 1

# git commit -am "remove vendor dirs"
# echo "clean-up vendor directories..."
# echo "Top 50 subtrees by size"

# git config core.hooksPath .githooks